### ISSUE TITLE
레이아웃 정리

### ISSUE THREAD

**Issue by rotoshine** [rotoshine/you-are-not-a-solitary-gourmet#1]
제곧내

**Comment by yogicat** [comment]
![detail](https://user-images.githubusercontent.com/35292501/42145394-34c27106-7dfc-11e8-8409-2ecacbc108af.png)
![main](https://user-images.githubusercontent.com/35292501/42145395-34eac534-7dfc-11e8-81a5-e546ea278b72.png)
![make](https://user-images.githubusercontent.com/35292501/42145396-35135bfc-7dfc-11e8-9dca-0f46b37eb650.png)

레이아웃 시안 작업 공유합니다. 이번주내로 사이트에 적용 예정임둥

**Comment by rotoshine** [comment]
👍
