### ISSUE TITLE
react-router 연동

### ISSUE THREAD

**Issue by rotoshine** [rotoshine/you-are-not-a-solitary-gourmet#14]
raect-router를 연동하여 목록 보기와 상세 보기의 페이지를 구분한다.

- [] react-router 세팅
- [] '상세 보기' url로 접근 시 조회 모달을 바로 띄우도록 수정

**Comment by colus001** [comment]
빨리해라 루카스

**Comment by stardustrain** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 오늘 합니다요
