### ISSUE TITLE
파티 창 열었을때 url바뀌면 그 url 쉐어할수 있음

### ISSUE THREAD

**Issue by hoi** [rotoshine/you-are-not-a-solitary-gourmet#42]
사람들한테 참석해달라고 슬랙으로 링크 쉐어하면서 말하고 싶을 것 같습니다

**Comment by rotoshine** [comment]
요 기능이 중요할 것 같습니다. 파티 생성 시 슬랙으로 메시지를 쏘는 김에 파티 url까지 같이 들어온다면 좋겠네요.

**Comment by rotoshine** [comment]
related #34

**Comment by colus001** [comment]
that's what i'm saying

**Comment by colus001** [comment]
Merged #48
